CREATE TABLE IF NOT EXISTS requests (
    id SERIAL PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    data_gb INTEGER NOT NULL,
    minutes INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);